version: "latest"

services:
  monkey-turtlebot:
    build:
      context: ./
      dockerfile: "Dockerfile"
    image: "monkey/humble/turtlebot"
    command: /bin/bash
    stdin_open: true ## docker run -i
    tty: true        ## docker run -t
    privileged: false
    # runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIB_GL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
      # - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    user: "monkey"
    volumes:
      ## Docker display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      ## Map folder
      - ./map:/home/monkey/map
  